import { defineStore } from 'pinia'

// Generate today's date for the report
const today = new Date()
const reportDate = today.toLocaleDateString('en-US', {
  weekday: 'long',
  year: 'numeric',
  month: 'long',
  day: 'numeric'
})

// Demo insights data for Element Fleet AI showcase - McKinsey-level analysis
const DEMO_INSIGHT = {
  id: 'insight-demo-001',
  orgId: 'demo-org',
  createdAt: new Date().toISOString(),
  sections: {
    executive_summary: `# DAILY FLEET PERFORMANCE ANALYSIS
## ${reportDate} | Fleet Operations Dashboard

---

## 📊 EXECUTIVE SUMMARY

**Fleet Status:** 1,250 Total Vehicles | 1,147 Active | 92 In Shop | 11 Out of Service

### Yesterday's Key Metrics

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
| Total Miles Driven | 187,432 miles | — | ✓ |
| Total Deliveries | 4,827 packages | 5,000 | ⚠️ |
| Fuel/Energy Cost | $42,318 | $38,000 | ⚠️ |
| Safety Score | 87/100 | 90/100 | ↓3 from last week |
| On-Time Delivery | 91.2% | 95% | ⚠️ |
| Cost per Mile | $0.58 | $0.52 | ⚠️ |

---

## ⚠️ CRITICAL ALERTS

| Priority | Alert | Estimated Impact |
|----------|-------|------------------|
| 🔴 Critical | Three crashes yesterday | $47,000 estimated damage |
| 🔴 Critical | EV battery degradation | 12 vehicles affected |
| 🟠 High | Lease mileage alerts | 27 vehicles over pace |
| 🟠 High | Insurance renewal | Premium increasing 18% |

---

## 💎 Today's Golden Nuggets

> **Nugget #1:** 87 delivery vans sat idle yesterday while paying $290/day in lease costs. Redistribution could save **$6,090/month**.

> **Nugget #2:** Fuel costs spike every Tuesday/Thursday (+18%). These are garbage collection routes using older trucks getting 5.2 MPG vs 7.8 MPG fleet average.

> **Nugget #3:** 73% of crashes happen to drivers with <6 months experience during 2-6 PM shift. Mandatory rest break at 3 PM could prevent **$180K annual losses**.

---

*Report generated by Element Fleet AI*
`,
    categories: {
      daily_overview: [
        {
          execution_id: 'daily-001',
          content: `## 🚛 FLEET UTILIZATION ANALYSIS

### Daily Utilization by Vehicle Type

| Vehicle Type | Utilization | Active/Total | Status |
|-------------|-------------|--------------|--------|
| Long-haul Trucks | 95% | 114/120 | ████████████████████ |
| Box Trucks | 82% | 205/250 | ████████████████░░░░ |
| Delivery Vans | 71% | 213/300 | ██████████████░░░░░░ |
| Service Vehicles | 62% | 124/200 | ████████████░░░░░░░░ |
| Sales Fleet | 53% | 106/200 | ██████████░░░░░░░░░░ |
| Executive | 42% | 21/50 | ████████░░░░░░░░░░░░ |

### Idle Asset Analysis

**87 delivery vans** sat completely idle yesterday while incurring:
- Lease payments: $290/day per vehicle
- Insurance: $12/day per vehicle
- Depreciation: $45/day per vehicle
- **Total daily cost of idle assets: $30,189**

### Redistribution Opportunity

| From Region | To Region | Vehicles | Demand Gap | Projected Revenue |
|-------------|-----------|----------|------------|-------------------|
| North Dallas | Arlington | 23 vans | High surge | +$8,740/day |
| Plano | Fort Worth | 18 vans | Moderate | +$5,220/day |
| Richardson | Downtown | 12 vans | High surge | +$4,680/day |

> **💎 Golden Nugget:** Implementing dynamic redistribution could capture **$558,000 additional annual revenue** while reducing idle costs by **$72,000/year**.
`
        }
      ],
      safety: [
        {
          execution_id: 'safety-001',
          content: `## 🛡️ SAFETY & RISK ANALYSIS

### Fleet Safety Score: 87/100 (↓3 from last week)

### Crash Frequency Analysis - Past 7 Days

| Day | 6-10 AM | 10 AM-2 PM | 2-6 PM | 6-10 PM | Total |
|-----|---------|------------|--------|---------|-------|
| Monday | • | • | ● | • | 1 |
| Tuesday | ● | • | ● | • | 2 |
| Wednesday | • | • | • | • | 0 |
| Thursday | • | ● | • | • | 1 |
| Friday | • | ● | ●● | ● | 4 |
| Saturday | • | • | • | • | 0 |
| Sunday | • | • | ● | • | 1 |

**Pattern Detected:** 78% of incidents occur during the **2-6 PM window**

### Driver Risk Distribution

| Risk Level | Driver Count | Percentage | Visual |
|------------|--------------|------------|--------|
| Low Risk (0-30) | 768 drivers | 60% | ████████████░░░░░░░░ |
| Medium Risk (31-70) | 384 drivers | 30% | ██████░░░░░░░░░░░░░░ |
| High Risk (71+) | 128 drivers | 10% | ██░░░░░░░░░░░░░░░░░░ |

### Yesterday's Incidents

| Unit | Incident Type | Location | Est. Damage | Status |
|------|---------------|----------|-------------|--------|
| #447 | Backing collision | Dallas depot | $12,000 | Under review |
| #892 | Sideswipe | I-35 northbound | $28,000 | Insurance filed |
| #234 | Parking lot | Customer site | $7,000 | Driver statement pending |

### Root Cause Analysis

| Factor | Contribution | Incidents | Trend |
|--------|--------------|-----------|-------|
| Driver fatigue (afternoon) | 42% | 4 | ↑ |
| Inexperience (<6 mo) | 31% | 3 | ↑ |
| Blind spot / backing | 18% | 2 | → |
| Weather conditions | 9% | 1 | ↓ |

> **💎 Golden Nugget:** 73% of crashes happen to drivers with <6 months experience during 2-6 PM shift. Implementing a **mandatory 15-minute rest break at 3 PM** could prevent an estimated **$180,000 in annual crash-related losses**.
`
        }
      ],
      fuel_efficiency: [
        {
          execution_id: 'fuel-001',
          content: `## 💰 COST PER MILE BREAKDOWN

### Yesterday's Operating Costs by Category

| Category | Cost/Mile | % of Total | vs Target | Trend |
|----------|-----------|------------|-----------|-------|
| Fuel/Energy | $0.226 | 39.0% | +$0.026 | 📈 |
| Maintenance | $0.142 | 24.5% | +$0.012 | 📈 |
| Insurance | $0.087 | 15.0% | +$0.017 | 📈 |
| Depreciation | $0.075 | 12.9% | -$0.005 | 📉 |
| Labor | $0.050 | 8.6% | On target | ➡️ |
| **TOTAL** | **$0.580** | **100%** | **+$0.060** | 📈 |

### Cost Trend - Last 30 Days

| Week | Cost/Mile | vs Target | Variance |
|------|-----------|-----------|----------|
| Week 1 | $0.54 | $0.52 | +$0.02 |
| Week 2 | $0.56 | $0.52 | +$0.04 |
| Week 3 | $0.55 | $0.52 | +$0.03 |
| Week 4 | $0.58 | $0.52 | +$0.06 |

**Concerning trend:** Cost per mile has increased **7.4% over 30 days**

### Fuel Cost Anomaly Detected

| Day | Fuel Spend | vs Average | Routes |
|-----|------------|------------|--------|
| Monday | $7,820 | Baseline | Standard |
| Tuesday | $9,228 | +18% | Garbage collection |
| Wednesday | $7,654 | -2% | Standard |
| Thursday | $9,412 | +20% | Garbage collection |
| Friday | $8,204 | +5% | Extended hours |

**Root Cause:** Tuesday/Thursday garbage routes use older trucks averaging **5.2 MPG** vs fleet average of **7.8 MPG**

> **💎 Golden Nugget:** Replacing 8 oldest garbage route trucks with newer fuel-efficient models would save **$4,200/month** in fuel costs alone. ROI: 14 months.

---

## ⚡ EV vs ICE PERFORMANCE

### Total Cost of Ownership Comparison - Yesterday

| Powertrain | Cost/Mile | Energy Efficiency | Maintenance | TCO Rank |
|------------|-----------|-------------------|-------------|----------|
| EV | $0.42 | 3.2 mi/kWh | $0.04/mi | 🥇 Best |
| Hybrid | $0.51 | 42 MPG | $0.08/mi | 🥈 |
| Diesel | $0.58 | 7.8 MPG | $0.12/mi | 🥉 |
| Gasoline | $0.61 | 16.2 MPG | $0.10/mi | 4th |

### EV Charging Analysis

| Charging Location | % of Charging | Cost/kWh | Daily Spend |
|-------------------|---------------|----------|-------------|
| Depot (overnight) | 78% | $0.09 | $387 |
| Public DC Fast | 22% | $0.38 | $446 |

**Problem:** Public charging costs **4.2x more** than depot charging

**Lost Productivity:** 4.5 hours/day waiting at public chargers = **$675 labor cost**

> **💎 Golden Nugget:** Installing **8 additional Level-2 chargers** at depot for $24,000 would shift 10% more charging to overnight depot rates, saving **$4,200/month**. Payback period: **5.7 months**.
`
        }
      ],
      maintenance: [
        {
          execution_id: 'maintenance-001',
          content: `## 🔧 MAINTENANCE PREDICTIONS

### Vehicles Requiring Action - Next 7 Days

| Urgency | Vehicle Count | Visual | Action Window |
|---------|---------------|--------|---------------|
| 🔴 Critical (Today) | 12 vehicles | ████ | Immediate |
| 🟠 High (1-3 days) | 24 vehicles | ████████ | This week |
| 🟡 Medium (4-7 days) | 38 vehicles | ████████████ | Schedule now |

### AI-Powered Breakdown Probability Model

| Unit # | Vehicle Type | Failure Prob. | Predicted Issue | Est. Cost | Downtime |
|--------|--------------|---------------|-----------------|-----------|----------|
| 782 | Freightliner | **87%** | Transmission | $8,500 | 5 days |
| 445 | Ford Transit | 76% | Brakes | $1,200 | 1 day |
| 923 | Kenworth | 71% | Turbo failure | $4,800 | 3 days |
| 167 | Sprinter | 68% | DPF system | $2,800 | 2 days |
| 534 | Mack | 64% | Fuel injectors | $3,200 | 2 days |

### Predictive Maintenance Accuracy

| Prediction Type | Accuracy | Prevented Breakdowns | Cost Avoided |
|-----------------|----------|---------------------|--------------|
| Engine | 94% | 23 this year | $184,000 |
| Transmission | 89% | 8 this year | $68,000 |
| Brakes | 97% | 45 this year | $54,000 |
| Electrical | 82% | 12 this year | $36,000 |

> **💎 Golden Nugget:** Unit #782 is showing **identical pre-failure sensor patterns** to 3 previous transmission failures in your fleet. Performing preventive repair **today** costs $4,500 vs $8,500 + 3 extra days downtime if it fails on the road.

### Shop Performance Rankings

| Shop | Avg Turnaround | Quality Score | Cost Index | Rating |
|------|----------------|---------------|------------|--------|
| ABC Truck Center | 2.1 days | 96% | 1.00x | ⭐⭐⭐⭐⭐ |
| Fleet Pride | 3.8 days | 88% | 1.12x | ⭐⭐⭐⭐ |
| Johnson Diesel | 5.2 days | 82% | 0.95x | ⭐⭐⭐ |
| QuickFix Auto | 7.3 days | 71% | 0.88x | ⭐⭐ |

**Recommendation:** Shift 40% of work from QuickFix to ABC Truck Center. Same cost, **5.2 days faster** average turnaround.
`
        }
      ],
      driver_behavior: [
        {
          execution_id: 'driver-001',
          content: `## 🏆 PERFORMANCE RANKINGS

### Best Performing Drivers - Yesterday

| Rank | Driver | Miles | Safety Events | Efficiency | Score |
|------|--------|-------|---------------|------------|-------|
| 🥇 | Maria Rodriguez | 342 | 0 | 4.1 mi/kWh (EV) | 98 |
| 🥈 | James Wilson | 487 | 0 | 8.9 MPG (Diesel) | 96 |
| 🥉 | Sarah Chen | 218 | 0 | 52 MPG (Hybrid) | 95 |
| 4 | David Park | 312 | 0 | 7.8 MPG | 94 |
| 5 | Lisa Thompson | 289 | 0 | 3.8 mi/kWh | 93 |

### Worst Performing Units - Cost per Mile

| Unit # | Cost/Mile | Issue | Status | Action |
|--------|-----------|-------|--------|--------|
| 1247 | $1.82/mi | Check engine light | Limping mode | Pull from service |
| 447 | $1.54/mi | Post-crash | Using rental | Insurance claim |
| 892 | $1.41/mi | Excessive idle | Poor MPG | Driver coaching |
| 1089 | $1.28/mi | Route inefficiency | Long detours | Route optimization |
| 756 | $1.19/mi | Fuel theft suspected | Investigating | GPS analysis |

### Driver Behavior Trends

| Metric | This Week | Last Week | Change | Target |
|--------|-----------|-----------|--------|--------|
| Hard Braking Events | 234 | 287 | ↓ 18% | <200 |
| Speeding Events | 89 | 112 | ↓ 21% | <50 |
| Idle Time (hrs) | 1,847 | 1,923 | ↓ 4% | <1,500 |
| Seatbelt Compliance | 97% | 94% | ↑ 3% | 100% |

### Coaching Impact Analysis

| Driver | Before Coaching | After Coaching | Improvement | Monthly Savings |
|--------|-----------------|----------------|-------------|-----------------|
| M. Johnson | 72 score | 84 score | +17% | $340 fuel |
| S. Williams | 74 score | 86 score | +16% | $290 fuel |
| R. Davis | 76 score | 88 score | +16% | $310 fuel |

> **Coaching ROI:** $2,400 investment → $11,280 annual savings = **370% return**
`
        }
      ],
      compliance: [
        {
          execution_id: 'compliance-001',
          content: `## 📋 LEASE & DEPRECIATION ANALYSIS

### Lease Mileage Status

| Status | Vehicles | Projected Excess Charges | Visual |
|--------|----------|-------------------------|--------|
| Over by 20%+ | 8 | $32,000 | ████████ |
| Over by 15% | 12 | $28,000 | ████████████ |
| Over by 10% | 7 | $9,800 | ███████ |
| On Track | 892 | $0 | ████████████████████ |
| Under Pace | 331 | Credit potential | ████████████████████████ |

### Top Lease Concerns

| Unit | Over Mileage | Excess Charges | Monthly Payment | Recommended Action |
|------|--------------|----------------|-----------------|-------------------|
| 234 | 12,847 mi | $4,496 | $1,250 | Swap to low-mile route |
| 567 | 11,234 mi | $3,932 | $980 | Consider early buyout |
| 891 | 9,876 mi | $3,457 | $1,100 | Restrict to local only |
| 345 | 8,234 mi | $2,882 | $875 | Monitor weekly |
| 678 | 7,890 mi | $2,762 | $1,450 | Park 2 days/week |

### Mileage Swap Opportunity

**Problem:** High-mileage lease vehicles on long routes, owned vehicles on short routes

| Swap Pair | Current Setup | After Swap | Annual Savings |
|-----------|---------------|------------|----------------|
| Unit 234 ↔ Unit 901 | Lease→Long, Own→Short | Lease→Short, Own→Long | $4,496 |
| Unit 567 ↔ Unit 845 | Lease→Long, Own→Short | Lease→Short, Own→Long | $3,932 |
| Unit 891 ↔ Unit 772 | Lease→Long, Own→Short | Lease→Short, Own→Long | $3,457 |

> **💎 Golden Nugget:** Swapping high-mileage lease vehicles with owned vehicles on long routes would avoid **$72,000** in excess mileage charges this year with **zero additional cost**.

---

## 🗺️ ROUTE OPTIMIZATION INSIGHTS

### Route Efficiency Analysis - Yesterday

| Route | Planned Miles | Actual Miles | Overage | Extra Cost |
|-------|---------------|--------------|---------|------------|
| Dallas Urban | 847 mi | 981 mi | +134 mi | $77.72 |
| Fort Worth Industrial | 623 mi | 644 mi | +21 mi | $12.18 |
| Arlington Residential | 445 mi | 512 mi | +67 mi | $38.86 |
| Plano Business | 389 mi | 401 mi | +12 mi | $6.96 |

**Total excess mileage:** 234 miles = **$135.72/day = $49,538/year**

### Delivery Performance by Time Window

| Time Window | On-Time % | Deliveries | Issue |
|-------------|-----------|------------|-------|
| 6 AM - 10 AM | 97% | 1,247 | ✓ |
| 10 AM - 2 PM | 89% | 1,456 | Traffic buildup |
| 2 PM - 6 PM | 78% | 1,523 | ⚠️ School traffic |
| 6 PM - 10 PM | 92% | 601 | ✓ |

> **💎 Golden Nugget:** 2-6 PM deliveries fail due to school traffic patterns. Starting afternoon routes **1 hour earlier** would improve on-time delivery by **11%** and save **134 miles/day** ($49K/year).
`
        }
      ],
      telematics: [
        {
          execution_id: 'telematics-001',
          content: `## 💵 FINANCIAL SUMMARY

### Yesterday's P&L Impact

**Revenue**
| Source | Amount |
|--------|--------|
| Deliveries Completed | +$287,432 |
| Fuel Surcharges | +$18,234 |
| Rental Income | +$2,100 |
| **Total Revenue** | **$307,766** |

**Expenses**
| Category | Amount | vs Budget |
|----------|--------|-----------|
| Fuel/Energy | -$42,318 | +11% |
| Maintenance | -$26,234 | +8% |
| Insurance (Daily) | -$16,234 | +18% |
| Labor | -$92,340 | On budget |
| Depreciation | -$14,234 | On budget |
| Incidents/Crashes | -$47,000 | Unplanned |
| **Total Expenses** | **-$238,360** | +14% |

**Net Operating Profit: $69,406** (22.5% margin)

### Month-to-Date Performance

| Metric | Actual | Target | Status |
|--------|--------|--------|--------|
| Revenue | $3,234,567 | $3,369,000 | 96% ⚠️ |
| Expenses | $2,645,890 | $2,449,898 | 108% ⚠️ |
| EBITDA | $588,677 | $707,490 | 83% ⚠️ |
| EBITDA Margin | 18.2% | 21.0% | Below target |

---

## ✅ RECOMMENDED ACTIONS

### Immediate (Today)
| Priority | Action | Impact | Owner |
|----------|--------|--------|-------|
| 🔴 | Pull Unit #782 from service - transmission failure imminent | Avoid $4,000 additional damage | Maintenance |
| 🔴 | Reassign 27 lease vehicles to shorter routes | Avoid $72K excess charges | Operations |
| 🟠 | Lock in diesel contract before tonight's price increase | Save $0.08/gal | Procurement |
| 🟠 | Deploy 8 idle vans to Arlington surge | Capture $8,740 revenue | Dispatch |

### This Week
| Priority | Action | Impact | Timeline |
|----------|--------|--------|----------|
| 🟠 | Install depot EV chargers | $4,200/mo savings | Mon-Wed |
| 🟠 | Implement 3 PM rest break policy | Reduce crashes 23% | Tuesday |
| 🟡 | Audit Tue/Thu fuel consumption | Identify 18% cost spike | Wed-Thu |
| 🟡 | Negotiate shop rate consolidation | 40% faster turnaround | Friday |

### This Month
| Priority | Action | Impact | ROI |
|----------|--------|--------|-----|
| 🟡 | Sell/trade 12 oldest diesels | $84K annual maintenance savings | 8 months |
| 🟡 | Expand EV pilot program | $0.16/mi savings on urban routes | 14 months |
| 🟢 | Driver coaching program expansion | $180K crash reduction | 3 months |

---

## 📈 TOTAL IDENTIFIED SAVINGS

| Opportunity | Annual Impact | Implementation |
|-------------|---------------|----------------|
| Lease mileage rebalancing | $72,000 | Immediate |
| Fuel price hedging | $165,000 | This week |
| Depot charging expansion | $84,000 | This month |
| Afternoon break policy | $180,000 | This week |
| Shop consolidation | $240,000 | This month |
| **TOTAL** | **$741,000** | — |

---

## 🚨 ALERTS SET FOR TOMORROW

- ⛔ Unit #782 - DO NOT DISPATCH (transmission)
- ⚠️ Driver Thompson - Fatigue monitoring required
- 💰 Fuel price increase at midnight
- 🔧 12 vehicles due for PM service
- 🏈 Cowboys game - adjust downtown routes
- ⛈️ Weather alert - thunderstorms 2-6 PM

---

*Report Generated: ${new Date().toLocaleString()}*
*Next Update: Tomorrow at 6:00 AM*
*Distribution: Fleet Manager, COO, CFO, Safety Director*

**Questions?** Contact Fleet Analytics Team ext. 2100
`
        }
      ]
    }
  }
}

export const useInsightsStore = defineStore('insights', {
  state: () => ({
    insight: null,
    loading: false,
    error: null,
  }),

  actions: {
    async load() {
      this.loading = true
      this.error = null

      try {
        // Use demo data instead of API call
        this.insight = DEMO_INSIGHT
        return this.insight.sections?.executive_summary || ''
      } catch (err) {
        this.error = err.message
        return this.getContent()
      } finally {
        this.loading = false
      }
    },

    get() {
      return this.insight || DEMO_INSIGHT
    },

    getContent() {
      return this.insight?.sections?.executive_summary || DEMO_INSIGHT.sections.executive_summary
    },
  },
})
